# Generated by Django 2.1.3 on 2019-02-02 07:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=stdimage.models.StdImageField(blank=True, default='profile.jpg', upload_to='profile_pic/'),
        ),
    ]
