# Generated by Django 2.1.3 on 2019-02-02 08:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=stdimage.models.StdImageField(default='profile.jpg', upload_to='profile_pic/'),
        ),
    ]
